using G14_ReviewDoAn.Data;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Security;
using System.Web.SessionState;

namespace G14_ReviewDoAn
{
    public class Global : System.Web.HttpApplication
    {

        protected void Application_Start(object sender, EventArgs e)
        {
            if (Application["USER_LIST"] == null)
                Application["USER_LIST"] = new List<Users>();
            List<Users> alUsers = (List<Users>)Application["USER_LIST"];
            alUsers.Add(new Users("Nguyen", "Huyen", "Nguyễn Huyền", "hn635221@gmail.com", "Abcdef123"));
            alUsers.Add(new Users("Nguyen", "Hang", "Nguyễn Hằng", "hang12@gmail.com", "Abcdef123"));
            alUsers.Add(new Users("Nguyen", "Lan", "Nguyễn Lan", "lan01@gmail.com", "Abcdef123"));


            Application["sanpham"] = new List<Product>();
            List<Product> listsp = (List<Product>)Application["sanpham"];
            //1.n ảnh nhà hàng
            listsp.Add(new Product("1.1", "1", 1, "Lẩu băng chuyền Kichi Kichi-AEON Mall Long Biên", "Tầng 3, AEON Mall Long Biene, 27 Cổ Linh, Quận long Biên, Hà Nội", "Images/Ảnh Nhà Hàng/lau-kichi.jpg", "Cảm nhận khi tôi bước vào đây là 1 không gian hoài cổ pha với những ánh đèn vàng, nó góp phần tạo lên 1 không gian sang trọng khi tôi thưởng thức những món ăn. Với những thực phẩm sạch, thịt bò mỹ tươi sạch, hải sản phong phú, nhiều món thật và tươi ngon với 1 mức giá ko khá là quá cao trong phân khúc giá được gọi là bình dân. Mình đã đi ăn khá nhiều quán nhưng lẩu băng chuyền kichi kichi là một nhà hàng mà làm mình thoả mãn nhất. Đến kichi đồ nhúng thì đa dạng, thích gì thì tự lấy trên chuyền, nhân viên lại nhiệt tình, chắc chắn sẽ quay lại nhiều lần. Mình nghĩ các bạn khi qua địa điểm này ko thể bỏ qua nó"));
            listsp.Add(new Product("1.2", "1", 0, "Cơm Niêu Tố Uyên - Phạm Ngọc Thạch", "102 C2 Phạm Ngọc Thạch, Quận Đống Đa, Hà Nội", "Images/Ảnh Nhà Hàng/com-nieu.jpg", "Đồ ăn ngon nhưng mà quá đắt. 1.Nhân viên: không nhiệt tình, bàn mình bị quên món nên phải nhắc lại nhân viên, thời gian phục vụ giữa các món hơi lâu. Không có thực đơn, tốt nhất là nên đứng ngay tại chỗ gọi. 2.  Cửa hàng bán cơm theo giờ thôi, ra sớm còn dc ăn chứ tầm 9h ra là thôi bảo vệ xua tay ko cho vào. Tầm giờ trưa, tối quán cũng khá đông. 3. Giá cả: cơm niêu Tố Uyên cực cực đắt, đắt so với những quán cơm khác, đồ ăn đa dạng. 4.Quán ồn ào! Ai k sợ đắt thì cứ qua ăn cơm ở đây nhé"));
            listsp.Add(new Product("1.3", "1", 0, "Bò Bít Tết Kiểu Pháp - Cube Beefsteak & Drinks", "20 Ngõ 211 Xã Đàn,  Quận Đống Đa, Hà Nội", "Images/Ảnh Nhà Hàng/bo-bit-tet.jpg", "Một địa chỉ ăn beefsteak ngon rẻ, chất lượng hoàn toàn oke đây ạ.- Không gian: Quán nằm trong ngõ nên rất thoáng và yên tĩnh. Tầng 1 rộng bao gồm bàn đông người và đi riêng. Tầng 2 không gian riêng tư hơn dành cho couple. Tầng 2 còn có khu làm bánh mì riêng nữa thơm mùi bánh dễ chịu lắm.- Đồ ăn: Mình gọi bít tết sốt tiêu đen và bít tết sốt BBQ size lớn. Đồ ăn ra khá nhanh, lúc order mình có gọi thịt medium, thịt chín vừa, rất mềm vừa dễ cắt vừa đậm sốt. Khoai chiên ăn kèm cũng rất vàng và giòn.Ngoài ra mình có gọi thêm salad dâu, mình cũng nghĩ là salad với dâu nhưng là dưa chuột, cà chua, xà lách ăn kèm sốt dâu: Điều đặc biệt ở đây khiến mình thích nhất chính là phần bánh mì tự làm. Mỗi bánh mang ra dù đã để 1 lúc nhưng bánh vẫn còn ấm nóng. Khi bẻ đôi bánh ra thì cực mềm, thơm và đặc ruột. Một suất này là mình thấy no căng bụng.- Điểm trừ là nhân viên chưa nhiệt tình lắm, phục vụ nhanh nhẹn.- Giá cả từ 99k/suất"));
            listsp.Add(new Product("1.4", "1", 1, "Lẩu Nướng Không Khói - Habit BBQ", "1A Dịch Vọng Hậu,  Quận Cầu Giấy, Hà Nội", "Images/Ảnh Nhà Hàng/lau-nuong-khong-khoi.jpg", "Cảm nhận đầu tiên khi tới Habit BBQ là không gian tương đối rộng rãi và sang trọng. Nhân viên khá nhanh nhẹn mang đồ ăn ra ngay sau khi bọn mình ngồi xuống. Đồ ăn: đa dạng, có mấy món như dẻ sườn, nạc vai ngon nhất là ăn với sốt cay.đa dạng cấc loại thịt bò, gà, heo, Đồ rất tươi. Hải sản thì khá đa dạng có tôm, mực, bạch tuộc, sashimi nhưng k có ghẹ, nếu là tín đồ hải sản thì đồ hải sản hơi thiếu. Mình ăn lẩu thái thấy khá ngon, ngọt, thơm mùi vị cốt dừa. Không gian thì không cần bàn cãi vì rất to và rộng. Không gìan sang trọng phù hợp tiếp khách và liên hoan công ty hay sinh nhật. Cuối cùng là phục vụ. Nhân viên ngoan, lễ phép, nhanh nhẹn. Sẽ tiếp tục đóng họ.Nhất là khu vực cầu giấy mình thấy đây là 1 trong các nhà hàng đáng thử nhất ở khu vực cầu giấy Tổng quan thì thấy khá xứng đáng vs số tiền bỏ ra. Tuy hôm mình tới ăn khá đông cũng vài lần phải gọi nhân viên tới lần thứ 2 mới được nhưng nói chung dịch vụ đồ ăn ok. "));
            listsp.Add(new Product("1.5", "1", 1, "Gà Xào Phô Mai - King Dakgalb", "2A Nguyễn Khang, Quận Cầu Giấy, Hà Nội", "Images/Ảnh Nhà Hàng/ga-xao-pho-mai.jpg", "King Dakbalbi Nguyễn Khang. Quán King Dakbalbi này nằm ở trên đường Nguyễn Khang đối diện bờ sông.Quán có hai tầng, không gian cũng tương đối nhỏ nhưng sạch sẽ.Ở đây thì đèn trông cứ tối tối thế nào ấy.Menu ở King Dakgalbi thì là menu gà Hàn với các món Hàn.Ở đây được gọi nhiều nhất chắc là gà xào phô mai bắp cải.Một chảo gà phô mai khá là to và đầy nên ăn thường ngấy. Mình gọi gà sốt truyền thống và cơm kimchi.Panchan ăn kèm ở đây có salad, củ cải muối và kimchi.Cơm kimchi được mang ra trước, cơm được trộn với kimchi không quá cay mà khá vừa miệng, có quả trứng chiên ở trên.Còn gà sốt một con là 250k, có thể gọi một nửa con là 125k.Sốt gà thì hơi đậm và cay so với khẩu vị của mình.Còn gà thì ăn cũng tạm được nhưng vì thịt trong trắng mà vỏ thì cay và đầy sốt nên ăn hơi ngấy.Nói chung ăn cũng ổn và giá cũng phù hợp. Nhân viên và chị chủ quán cũng thân thiện, phục vụ khá nhiệt tình nhanh chóng"));
            listsp.Add(new Product("1.6", "1", 0, "Cơm Chay - Nàng Tấm", "79A Trần Hưng Đạo, Quận Hoàn Kiếm, Hà Nội", "Images/Ảnh Nhà Hàng/nangtam.jpg", " Tên quán thì nghe nói đến cũng khá lâu rồi nên quyết định ra thưởng thức luôn. Không gian: Quán nằm trong ngõ trên đường Trần Hưng Đạo, thật ra cũng rất dễ tìm vì nằm cùng phía với Lẩu cua Khôi.Tuy nhiên là không gian quán hơi bé và bí trông cũng không bắt mắt lắm vì mình cứ hay bị thích những quán đèn vàng ấm áp nên cũng thấy không gian quá ư bình thường. Đồ ăn: Vì đi có 2 người lại lần đầu ăn nên đành lục lại review của người đi trước để chọn món. Đồ ăn nói chung là ổn, mình có gọi măng trúc xào thịt bò, bò cuộn lá lốt, cơm chiên và 1 món gi đó làm từ váng đậu ngon thần sầu, ngậy thơm quá đỉnh.Đồ ăn nóng hổi gọi chừng 10' là có ngay nên cơn đói chưa kịp đến đã phải đi😝. Phục vụ: Nhân viên phục vụ nhanh, nhiệt tình. Giá cả: Giả cả cũng tầm trung, có 1 số món giá hơi cao hơn so với 1 số quán chay mình đã thử quá, 2 người nói chung hết 300k nhưng mà bạn mình vẫn chưa đủ no😝. Sẽ quay lại và thử các món khác để đánh giá tiếp😎"));
            listsp.Add(new Product("1.7", "1", 0, "Bún Bò Huế - Madame Lân", "301 Tô Hiệu, Quận Cầu Giấy, Hà Nội", "Images/Ảnh Nhà Hàng/bunboHue.jpg", "Đồ ăn ngon: Về quán ăn: Quán tìm rất dễ vì năm trên mặt đường và cũng khá to và sáng sủa nên kể cả buổi sáng hay tối đi đến đều tìm rất dễ. Bên ngoài thì quán nhìn cũng khá bình thường như bao quán ăn hạng trung bình trở len khác, nhưng khi vào khu sân bên trong thì mình cảm thấy ấn tượng hẳn.Quán ăn sáng sủa buổi tối có đèn treo, có thể sáng hơn một tí nhưng nhìn chung là ổn.Sạch sẽ gọn gàng ghế bàn đều ổn cả. Đồ ăn: Mình biết bún bò huế cũng được hơn hai năm rồi và cũng đa thử nhiều nơi, tuy mình cũng hơi khó tính trong chuyện ăn uống nhưng cảm thấy đồ ăn ở đây nhất là bún bò huế ăn khá ngon. Cái mình thấy được ở đây nhất là tuy quán nhìn sang trọng nhưng đồ ăn rất ngon ma giá cả lại rất phải chăng. Phục vụ: Đồ ăn được phục vụ RẤT NHANH. Mình vừa gọi đợi mới khoang 3 phút thôi đã mang ra ròi:)) nói chung rất tốt. Phục vụ ở đây cũng dễ chịu. Nói chung tất cả đều ổn. Nếu có dịp mình sẽ lại về đây ăn để thử hết món ở đây vì đợt này có it thời gian quá ♥️"));
            listsp.Add(new Product("1.8", "1", 0, "Mì Cay 7 Cấp Độ Hàn Quốc - Sasin", "219 Nguyễn Ngọc Vũ, Quận Cầu Giấy, Hà Nội", "Images/Ảnh Nhà Hàng/micay.jpg", "Sasin - 219 Nguyễn Ngọc Vũ. Đói bụng là ghé vào làm bát mỳ cay 7 cấp độ, nhất là vào mùa đông ăn ấm người vô cùng.Vị nào của quán cũng ngon, quán cũng có rất nhiều món ăn vặt, ăn nhẹ đi kèm.Bát mỳ trông ưng ý vô cùng, đầy đặn, ăn lại ngon, không cay quá, lần nào cũng đầy đủ như này.Tôm ở đây ăn rất ngon, thịt tôm ngọt kiểu vị ngọt tươi của tôm. Không gian ấm cúng, bàn ghế sạch sẽ, nhà vệ sinh ở đây hơi bẩn chút, có lẽ vì đông khách nên nhân viên quán không để ý khu vực này. Nhân viên nhanh nhẹn, chủ quán rất nhiệt tình, bảo vệ cũng tận tình dắt xe cho mình.Giá lại ở mức vừa phải đối với chiếc bụng đang đói cồn cào"));
            //2.n ảnh đồ ăn vặt
            listsp.Add(new Product("2.1", "2", 0, "Bánh Gà Thần Thánh - 158 Hồng Mai", "11 Ngõ 158 Hồng Mai,  Quận Hai Bà Trưng, Hà Nội", "Images/Ăn Vặt/banh-ga-than-thanh.jpg", "Quán này ngay cạnh trường mình nên quá quen thuộc rồi :))). Bánh gà ở đây được đánh giá là ngon nhất, best nhất.Dù sau này có thêm nhiều chỗ cũng làm bánh gà nhưng vẫn thích hương vị ở đây nhất! Bánh gà trước 4k / c, bây giờ 5k rồi, bánh to, vừa rán xong thơm lắm luôn, lớp bột bên ngoài giòn giòn còn bên trong là nhân gà nóng, mềm mềm chấm sốt hay tương ớt thì đỉnh luôn.Món này học sinh sinh viên ăn thích lắm nhé!!! Cứ chiều chiều hoặc đói là ra làm 3 - 4 cái đủ ngang bụng rùi! Tuy nhiên ở đây mình chỉ thích bánh gà, thích chất lượng bánh thôi chứ không gian quan cực nhỏ, rất nhỏ, chỉ có vài cái ghế ngồi ở đường và rất hay đông, chỗ ngồi đất còn không sạch lắm, mà ra mấy lần toàn chưa có với hết, nên cũng hơi bực:)) Nói chung các bạn cứ mua về ăn cho tiện, hoặc đặt ship về ý, đỡ phải đi. Lớp mình liên hoan cũng hay đặt, ngon!"));
            listsp.Add(new Product("2.2", "2", 0, "Bánh Mì Cô Long - Nguyễn Chí Thanh", "29 Nguyễn Chí Thanh, Ba Đình, Hà Nội", "Images/Ăn Vặt/banh-mi-co-long.jpg", "Đồ ăn ra nhanh, chờ tầm 2-3p đã ra mặc dù quán có vẻ thiếu nhân viên. Thịt bò mềm, thơm ướp đậm vi ăn ngon nhưng thích hơn vẫn là vị pate từ hồi bà Long làm, ăn không trượt đi đâu được thơm và hơi ngậy ngậy. Bánh mì lò đất, ăn thơm mềm đúng vị truyền thống ngày xưa, chỉ có không hài lòng là dưa góp ăn cay quá, mất hết cả ngon. Chảo nóng hổi và sốt còn đang lục bục sôi. Bánh mì ấm, vỏ ngoài giòn rụm, bên trong thì mềm, cắn hay xé bánh ko lo bị dai. Khoai tây với xúc xích thì không có mấy để phát biểu, ăn rất bình thường. Sốt ăn vừa miệng, có chút vị cà chua nên khá ngon. Kết hợp sốt với pate thì trở thành combo tuyệt hảo. Phải gọi bánh thứ 2 mà ăn ngấu nghiến mấy phút đã hết sạch. Chỉ tiếc là ko gọi suất thứ 2 ăn tiếp vì sợ no quá. Quán tương đối sạch sẽ, chỗ ngồi rộng rãi, giá cả phải chăng.Đáng thử cho những ai đang thèm bánh mì chảo."));
            listsp.Add(new Product("2.3", "2", 0, "Chân Gà Rang Muối - Hàng Thùng", "14 Hàng Thùng,  Quận Hoàn Kiếm, Hà Nội", "Images/Ăn Vặt/chan-ga-rang-muoi.jpg", "Quán này nổi tiếng lâu rồi. Vị trí: gần bờ hồ, ở trung tâm nên rất thuận tiện cho các hoạt động khách. Không gian: quán nhỏ, mình đến lúc khách đông nên ngồi hơi chen chúc, tuy nhiên lúc đó đang là mùa lạnh nên thấy ấm cúngThích mỗi chân gà rang muối ở đây thôi. Có 2 cửa hàng trên phô hàng thùng. Quán có hai tầng ngồi thoải mái. Quán có thêm cả lẩu nữa thì phải. Mình gọi chân gà rang muối, chiên mắm và khoai tây chiên. Nước chấm nhìn đơn giản mà chấm ngon phết. Chân gà to nhiều thịt chấm ngọt ngọt chua chua ăn ngon. Khoai tây là loại đóng gói sẵn rồi chiên lên. Giá khoảng 60 - 80k / người. Điểm trừ là order đợi chờ hơi lâu và quán hơi ồn."));
            listsp.Add(new Product("2.4", "2", 0, "Kem Xôi Chè Thái Lan - Giảng Võ", "289 Kim Mã (117 A5 TT Giảng Võ ), Quận Ba Đình, Hà Nội", "Images/Ăn Vặt/kem-xoi-che.jpg", "Ây gu, mình nếu không phải fan thì chắc cũng phải là khách ruột của quán rồi. #vịtrí: Quán này mở chắc cũng phải ngót nghét hơi 20 năm rồi. Mình nhớ hồi đầu quán ở chỗ đường Phan Đình Phùng cơ, còn chuyển về Kim Mã chắc cũng phải tầm hơn chục năm gì đấy. #Kemxôi: mình thì mình khuyên chân thành là bạn nào muốn ăn thử cả 2 món như mình thì các bạn nên ăn chè trước, ăn kem xôi sau. Vì kem xôi ngọt hơn so với chè kinh khủng, nên khi ăn kem xong chuyển sang chè, mình cảm giác như bị mất vị giác vậy. Điểm cộng cho món kem xôi và cũng là điểm đặc biệt của quán khác hoàn toàn với các chỗ bán kem xôi khác đó chính là Dừa khô. Ở đây là dừa khô tự làm, rất lạ(như kiểu cùi dừa được sấy lên ý), chứ không phải là dừa khô trong các túi bán sẵn đâu. Xôi được hấp lá dứa, rất thơm, ngậy và bùi. Kem thì hơi ngọt xíu. Về tổng thể thì Kem xôi ở đây đứng vị trí no1 trong lòng mình hahaa. #ChèThái: về cơ bản thì gọi là tạm ổn, gọi là chè thái nhưng thực chất k có cái xanh xanh mà người ta hay gọi là chè thái đâu. Dạo gần đây mình ăn thì hình như là bị ninh quá tay ý, trân châu + thạch (giống vỏ sò ý) hơi bị nát. Các bạn nên ăn thử 1 lần, raasrt ngon."));
            listsp.Add(new Product("2.5", "2", 0, "Tào Phớ Nghĩa Tân", "106C2 Nghĩa Tân,  Quận Cầu Giấy, Hà Nội", "Images/Ăn Vặt/tao-pho.jpg", "Tào Phớ Nghĩa Tân: 🔸 Quán ở khu đối diện cổng trường nghĩa tân, khu này có bán cả bánh gối cũng rất ngon nhé, có cả Cột điện quán nữa. 🔸 Quán bé, cũng đông, hơi ẩm mốc, k được sạch.Ngồi bên ngoài thì thích hơn, bên trong hơi bí.Mình gọi tào phớ đầy đủ, một bát ú ụ một đống topping mà có 7k thui.Ăn một bát là chắc cũng k cần ăn cơm rồi.Nhưng mình thấy k chất lượng lắm, nước đường ngọt lử, k thơm thơm vị thanh thanh như chỗ khác.Trân châu ăn tùy hôm, có hôm cũng nát lắm.Được cái rẻ với tiện ăn vặt các món khác thôi"));
            listsp.Add(new Product("2.6", "2", 0, "Xôi Sườn Cay - 628 Trường Chinh", "628 Trường Chinh,  Quận Đống Đa, Hà Nội", "Images/Ăn Vặt/xoi-suon-cay.jpg", "~ Quán xôi này nổi tiếng ở khu vực Ngã Tư Sở và rất đông khách. Đây là lần đầu tiên mình ngồi ăn tại quán còn bình thường toàn mua về và khách mua về ở đây cũng đông. Quán có chỗ để xe khá thoải mái. Trong nhà thì không trang trí gì đặc sắc, có mấy cái bàn để khách ngồi lại ăn. Menu có khá nhiều món xôi và giao động từ 20 - 30k, có cả các loại nước uống và sữa.Mình gọi một xôi gà xé. Xôi khá mềm nhưng tương đối ít, gà xé thì cho nhiều, có điều hơi khô nhưng được cái ướp thấm nên cũng kéo lại được. Sườn mềm, nhiều thịt, thấm vị đậm đà. Ko quá cay, pate siêu ngon, rất thơm ko hề hôi. Cảm giác làm bằng thịt và gan chất lượng ý. Mùi vị giống pate mẹ làm ở nhà luôn, gà xé khô và nhạt mình ko thích, xôi cuối ngày mà vẫn mềm dẻo và nóng hổi ý. Hạt xôi vàng ươm dẻo vừa ko khô ko nát. Bóng bẩy thích dã man, cuối ngày hết dưa muối, cô ý cho luôn dưa chuột tươi haha.Ngon giòn mát đỡ ngấy. Quán đông khách nhưng phục vụ nhanh và giá cả bình dân."));
            listsp.Add(new Product("2.7", "2", 1, "Nem Lụi & Bánh Xèo - Nguyễn Khuyến", "89 Nguyễn Khuyến,  Quận Đống Đa, Hà Nội", "Images/Ăn Vặt/nem-lui-banh-xeo.jpg", "Về vị trí: nằm ở 89*** đi qua thấy biển bánh xèo to to là nó đó 😀. Về không gian: không quá rộng và cũng không được sạch sẽ cho lắm.Chắc do buổi trưa khách đến ăn đông mà cũng ý thức kém nên... Về đồ ăn: Mình đi 3 người gọi 6 bánh xèo và 12 nem lụi, ăn khá no. Bánh xèo giòn, thơm nhưng nhân hơi ít ))) Nem lụi thì ngon, thịt chắc, tẩm ướp đậm đà nên khá đưa miệng 😍. Về giá cả: Siêu hợp lý, chỉ từ 5k / nem lụi và 10k / bánh xèo 😍. ❤️ Độ phục vụ thì thân thiện khỏi nói, đông khách đến mấy cũng thấy mọi người nhẹ nhàng mỉm cười chứ không quát tháo khách gì cả. Nói chung là tuần nào tụi mình cũng ra đây ăn, bị nghiện mất rồi ạ ❤️"));
            listsp.Add(new Product("2.8", "2", 1, "Chân Gà Hấp Sả Ớt Mắt To", "23 - 24 Lương Ngọc Quyến,  Quận Hoàn Kiếm, Hà Nội", "Images/Ăn Vặt/chan-ga-xa-ot.jpg", "Chân Gà Hấp Sả Ớt Mắt To. Quán nằm ở phố đi bộ nè. Ngon bá cháy lun. Chân gà ngâm sả ớt chấm sốt mặn cay giá 50k 5 chân và chân gà chiên mắm ớt chấm sốt chua ngọt giòn tan luôn giá 50k 4 chân. Nhân viên phục vụ nhiệt tình thoải mái. Rất phù hơph tụ tập bạn bè anh chị em bạn dì đi nhậu tám chuyện hết xảy lunn. Có dịp vào phố đi bộ kiểu gì cũng phải ghé quán ạ"));
            //3.n ảnh quán ăn
            listsp.Add(new Product("3.1", "3", 1, "Bánh Canh Ghẹ 69 - Ô Chợ Dừa", "32 Ô Chợ Dừa Mới (69 Ô Chợ Dừa Cũ),  Quận Đống Đa, Hà Nội", "Images/Quán Ăn/banh-canh-ghe.jpg", "Về vị trí quán nằm ngay mặt đường tuy nhiên ở ô chợ dừa đánh số lung tung nên lần đầu tìm hơi lâu, không gian: rộng rãi, thoáng mát. Đồ ăn mình thấy khá ngọt điển hình của đồ miền trong. Bọn mình ăn vắt thêm 3 4 quả quất thì mới thấy vừa. Một bát khá đầy đủ nhiều topping. Bọn mình gọi bát 55k và 1 bát ngao thêm thì thấy khá no. Món ngao nước chấm rất chi là ngon vừa miệng. Chỗ ngồi mình thấy hơi nhỏ bất tiện chút nếu đi hội đông người. Mình nghĩ bàn ở quán ngồi tầm 2 - 4 người thì vừa, không hợp đi quá đông, nhân viên: phục vụ nhanh và khá nhiệt tình."));
            listsp.Add(new Product("3.2", "3", 0, "Xôi Yến - Nguyễn Hữu Huân", "35B Nguyễn Hữu Huân, Quận Hoàn Kiếm, Hà Nội", "Images/Quán Ăn/xoi-yen.jpg", "Xôi yến: 🌸 Vị trí: quán nằm ở con phố nguyễn hữu huân, con phố quá là trung tâm ăn uống tụ tập rồi.Đi qua là nhìn thấy quán luôn vì biển hiệu to đùng và rất là to a.Ko gian bên trong tương đối, có chỗ ngồi trong nhà khá nhiều tuy nhiên ngồi hơi sát nhau nhé. 🌸 Giá cả: thuộc tầm giá trung bình, khoảng 35 - 50k 1 suất xôi. 🌸 Chất lượng: bao nhiêu năm thì mình thấy xôi yến vẫn là 1 trong những hàng chất lượng nhé. Đặc biệt mình rất thích ăn xôi gà ở đây. Phần xôi làm mềm dẻo cộng thêm phầm topping ngon. Ngoài ra khẩu phần 1 suất khá là nhiều luôn đó."));
            listsp.Add(new Product("3.3", "3", 1, "Cơm Rang Gà Quay - Bà Triệu", "29 Bà Triệu, P. Hàng Bài, Quận Hoàn Kiếm, Hà Nội", "Images/Quán Ăn/com-rang-ga-quay.jpg", "Không gian: quán có ngồi ở vỉa hè, thoáng đãng, full bàn lại phải lên tầng 2 hơi bí bí một chút. Quán chia làm 2 khu vực bán cạnh nhau ngồi vỉa hè cũng rộng rãi lắm không bị chật đâu. Phục vụ: trời ơi phục vụ nhanh dã man.Vì gà được làm trước với cơm chỉ cần rang lên thôii nên ord cơm rang gà quay auto 1 phút có luôn 👏🏻👏🏻👍🏻. Đồ ăn: như tiêu đề, best luôn ạ:))) nước sốt cà chua thần thánh làm tăng thêm độ ngon của món này 1000 % luôn(minh chứng là lần nào cũng phải gọi thêm 1 bát sốt).Gà tẩm ướp vừa phải, da vẫn có độ giòn. À với lại gà ở đây là gà công nghiệp nhé nhưng vẫn rất ngon. 55k / suất gà quay(mua mang về 60k cà hộp). Bình thường ở đây mình toàn ăn cơm rang gà quay nên chỉ rw mỗi món này ))"));
            listsp.Add(new Product("3.4", "3", 0, "Bún Miến Lươn & Bánh Đa Cua - Quán Cây Xoài", "Mặt Sau 102B A4, Khu Tập Thể Bắc Thành Công,  Quận Ba Đình, Hà Nội", "Images/Quán Ăn/bun-mien-luon.jpg", "✔ Nhà mình thi thoảng lười nấu nên toàn lên đặt đồ ăn, quán này không bao giờ làm gia đình mình thất vọng. 🏠 Vị trí quán dễ tìm, đông người biết đến. 🌸 Không gian: phù hợp, nói chung rất thoải mái, view đủ đẹp để sống ảo nhưng dịch mua đồ ăn qua Now cho an toàn nha các bạn😂. 💰 Giá cả: rẻ, hợp lý mà chất lượng món ăn thì xứng với giá tiền, rất đáng để ăn. Nói chung là Ngon thực sự, mình thành fan ăn đều mỗi tuần mỗi tháng được hơn 1 năm nay rồi, mình dẫn bạn bè đi ăn ai cũng khen. Nói về không gian thì quán khá rộng rãi, có thể gọi đồ ăn về nhà để ăn. Giá của đồ ăn cũng rẻ. Bạn nào không thích ra quán có thể order họ sẽ mang tới."));
            listsp.Add(new Product("3.5", "3", 0,  "Bánh Cuốn Bà Hoành - Tô Hiến Thành", "66 Tô Hiến Thành, Quận Hai Bà Trưng, Hà Nội", "Images/Quán Ăn/banh-cuon-ba-hoanh.jpg", "Có lẽ, ấn tượng với những người đến ăn lần đầu đó là quán khá rộng, gồm 4 nhà mặt tiền với đội ngũ nhân viên phục vụ mặc đồng phục chỉnh trang, chuyên nghiệp. Không gian ở đây khá rộng rãi và thoải mái, mang nhiều nét truyền thống với những chiếc bàn, ghế gỗ đem lại cho mọi người cảm giác yên bình, mộc mạc, dân dã giữa lòng Hà Nội. Có thể ngồi trong nhà hoặc ngoài vỉa hè vừa thưởng thức vừa nhìn ngắm phố phường nhộn nhịp, tấp nập.Nhân viên khá nhanh nhẹn, chỉ cần gọi món vài phút, bạn đã có một mâm bánh cuốn đầy ắp.Bánh cuốn ở đây tráng không mỏng quá, cũng không quá dày, có độ dai tự nhiên, thơm mùi gạo mà không có vị chua, đúng kiểu bánh cuốn truyền thống.Chả quế ăn kèm không quá ngấy, miếng được thái đầy đặn, ăn có vị giòn và thơm.Thịt nướng với nước chấm cũng vừa phải không bị mặn.Rau thơm được phủ lên trên đĩa bánh cuốn rất tươi ngon. Nước chấm được pha vừa miệng và quyện với vị của bánh cuốn, vị thơm thơm ngọt ngọt của chả quế, thanh mát của rau mùi và những miếng hành khô phi giòn nức mũi."));
            listsp.Add(new Product("3.6", "3", 0, "Bún Ốc Bà Lương", "34 - 64 Ngõ 191 Khương Thượng,  Quận Đống Đa, Hà Nội", "Images/Quán Ăn/bun-oc.jpg", "Món ăn: nồi lẩu nghe đâu tầm 500k (do được mời mà menu ko để giá nên không nắm) mà to và đầy đồ ăn bên trong. Ốc tươi ngon, nước lẩu vị chua ăn rất bắt. Ngoài món chính là lẩu kết nhất món ốc xào chuối đậu và ốc xào lăn. Chả ốc và nem ốc hơi dầu mỡ nhưng được cái trẻ con thích. Khuyến cáo là 1 nồi lẩu dư sức cho 4-5 người lớn ăn nên nếu đã gọi lẩu thì đừng gọi các món khác. Không gian: quán kiểu nhà ở chuyển thành quán nên chỗ ngồi lịch sự, không gian sạch sẽ, nhà mình đi cùng em bé nhỏ cho bé bò chơi loanh quanh thoải mát có điều phải leo lầu hơi mất công chút. Phục vụ: anh chủ vui vẻ nhiệt tình, bé nhân viên hơi kém vì ko tư vấn nên bàn mình gọi quá nhiều ăn không hết còn dư quá trời phải gói mang về. Địa điểm: hẻm nhỏ phải đi bộ vào trong, anh chủ hướng dẫn rất nhiệt tình.Nguyên văn tin nhắn chỉ đường: Em xuống đường trường chinh rẽ vào phố khương thượng đi qua chợ 10m rẽ phải vào ngõ 191 số nhà 34 có đèn lồng đỏ treo alo anh đón em kẻo nhầm. Sđt anh chủ: 0912721458")); ;
            listsp.Add(new Product("3.7", "3", 0, "Bánh Tráng Trộn Tina Trần - 33 Chùa Láng", "3 A15 Ngõ 33 Chùa Láng, Quận Đống Đa, Hà Nội", "Images/Quán Ăn/banh-trang-tron.jpg", "* Về bánh tráng thì mình và bạn mình có gọi bánh tráng trộn bò khô, trộn thập cẩm, nướng tép hành và nướng xúc xích thịt. Tuy nhiên bánh tráng nướng ra sau nên mình chỉ kịp chụp bánh tráng trộn. Tất cả đều ngon, có lẽ do mình dễ ăn nên chẳng có gì để chê cả. * Về cút lộn xào me và bắp xào tôm: sốt me ngon đặm đà, ngon vừa miệng; bắp xào ngon nhưng hơi ít tôm. * Về đồ uống: trà đào và trà quất đều ổn. * Về không gian quán: sạch sẽ, thoáng mát. * Về nhân viên: có lẽ lúc mình tới quán ít khách nên các bạn làm đồ cho bọn mình rất nhanh, có bạn dễ thương cực lại còn nhiệt tình. *Về chị chủ quán: chị chủ xinh cả hiền, lúc nào cũng tươi chứ không gây áp lực cho khách như 1 số chỗ cục súc mình đã từng tới ăn"));
            listsp.Add(new Product("3.8", "3", 0, "Phở Thìn - Lò Đúc", "13 Lò Đúc, Quận Hai Bà Trưng, Hà Nội", "Images/Quán Ăn/pho-thin.jpg", "Mình thấy quán phở này nổi tiếng và được review là đã có từ lâu đời nên khi đến Hà Nội mình ghé qua ăn. Quán có không gian hơi nhỏ, khách thì rất đông. Khi vào cửa thì order luôn và tính tiền rồi lại bàn ngồi, cô chủ quán đọc order như máy luôn, khá ấn tượng, mình gọi 2 tô phỏ kèm quẩy giá 140k. Tô bún to, sợ bún nhỏ, ngon, nước lèo hơi nhạt, thịt bò thì được xào chín qua rồi thì phải, nên nhìn hơi nhiều dầu trong tô phở, theo mình thấy thì lượng thịt nhiều mà(không hiểu sao nhiều bình luận nói ít thịt), nếu không dặn trước thì hành ngò trong tô sẽ hơi bị nhiều. Nhân viên của quán nhanh nhẹn"));

            Application["sanpham"] = listsp;


        }

        protected void Session_Start(object sender, EventArgs e)
        {

        }

        protected void Application_BeginRequest(object sender, EventArgs e)
        {

        }

        protected void Application_AuthenticateRequest(object sender, EventArgs e)
        {

        }

        protected void Application_Error(object sender, EventArgs e)
        {

        }

        protected void Session_End(object sender, EventArgs e)
        {

        }

        protected void Application_End(object sender, EventArgs e)
        {

        }
    }
}